services:
  postgres:
    image: "postgres:17.0-alpine3.20"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=xachMtJ6lCLdnsR3318Eq8sWRzShcGq"
      - "PGDATA=/data/postgre"
    volumes:
      - "postgres-data:/data/postgres"

  redis:
    image: "redis:7.4-alpine3.20"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  soketi:
    image: "quay.io/soketi/soketi:1.6-16-debian"
    command: ["--config=/etc/soketi.json"]
    ports:
      - "6001:6001"
    volumes:
      - "./soketi.json:/etc/soketi.json"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
  redis-data:
